apiVersion : apps/v1
kind : Deployment
metadata : 
  name : worker-deployment
spec:
  replicas : 1
  selector:
    matchLabels:  #refers to the label that which pod should the deployment manage
      component : worker
  template:
    metadata:
      labels:   # create pod with the label named below
        component : worker
    spec:
      containers:
        - name: woker
          image: gurnoorsb/multi-worker
          env : 
            - name : REDIS_HOST
              value : redis-cluster-ip-service
            - name : REDIS_PORT
              value : "6379"
            

  
